version: '3'
services:
  backend:
    image: nginx:1.15.6
    container_name: backend
    ports:
      - '8000:80'
    depends_on:
      - php
    volumes:
      - ./docker/backend/default.conf:/etc/nginx/conf.d/default.conf
      #- ./app/backend:/var/www/html

  frontend:
    build: ./docker/node
    ports:
      - '3000:3000'
    volumes:
      - ./app/frontend:/var/www/html
    command: >
      bash -c "npm install &&
      npm rebuild node-sass &&
      npm run lintfix &&
      npm run dev"
    tty: true
    stdin_open: true

  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./app/backend:/var/www/html
      #- ./docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    # command: >
    #   bash -c "composer install &&
    #   php artisan migrate:refresh --seed --force &&
    #   /bin/bash"
    depends_on:
      - mysql
    tty: true
    stdin_open: true

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: haccp_dev
      MYSQL_USER: haccp_dev
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    tty: true
    # networks:
    #   app_net:
    #     ipv4_address: 172.0.0.1
  
    # command: >
    #   bash -c "create database haccp_dev; &&
    #   grant all privileges on haccp_dev.* to haccp_dev@localhost identified by 'secret'"
    # volumes:
    #   - ./docker/db/data:/var/lib/mysql
    #   - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #   - ./docker/db/sql:/docker-entrypoint-initdb.d

# networks:
#   app_net:
#     driver: bridge
#     ipam:
#      driver: default
#      config:
#        - subnet: 172.0.0.0/24

volumes:
  mysql-data:
  